// Données des catégories de dépenses publiques
// Sources : DREES 2024, INSEE COFOG 2024, Eurostat, OCDE

export interface DepenseCategory {
  id: string
  name: string
  icon: string
  color: string
  amount: number // en Md€
  description: string
  details: string[]
  // Données France
  france: {
    evolution: { year: string; value: number }[]
    breakdown?: { name: string; amount: number; percent: number }[]
    keyFacts: string[]
  }
  // Comparaison internationale
  comparison: {
    eu: { country: string; value: number; highlight?: boolean }[]
    oecd?: { country: string; value: number; highlight?: boolean }[]
    insights: string[]
  }
}

export const DEPENSES_CATEGORIES: DepenseCategory[] = [
  {
    id: 'retraites',
    name: 'Retraites',
    icon: '👴',
    color: '#ff6b6b',
    amount: 380, // Source: COR 2024 - Dépenses nettes (hors CSG/CRDS retraités)
    description: 'Pensions de retraite versées aux anciens actifs (tous régimes confondus)',
    details: [
      'Régime général (CNAV)',
      'Régimes complémentaires (AGIRC-ARRCO)',
      'Régimes spéciaux (SNCF, RATP, EDF...)',
      'Fonction publique',
      'Minimum vieillesse (ASPA)',
    ],
    france: {
      evolution: [
        { year: '2015', value: 308 },
        { year: '2016', value: 314 },
        { year: '2017', value: 320 },
        { year: '2018', value: 326 },
        { year: '2019', value: 333 },
        { year: '2020', value: 340 },
        { year: '2021', value: 350 },
        { year: '2022', value: 360 },
        { year: '2023', value: 370 },
        { year: '2024', value: 380 },
      ],
      breakdown: [
        { name: 'Régime général (CNAV)', amount: 145, percent: 38.2 },
        { name: 'AGIRC-ARRCO', amount: 90, percent: 23.7 },
        { name: 'Fonction publique d\'État', amount: 60, percent: 15.8 },
        { name: 'Collectivités (CNRACL)', amount: 25, percent: 6.6 },
        { name: 'Régimes spéciaux', amount: 20, percent: 5.3 },
        { name: 'MSA (agricole)', amount: 18, percent: 4.7 },
        { name: 'Autres régimes', amount: 22, percent: 5.8 },
      ],
      keyFacts: [
        '17,2 millions de retraités en France (2024)',
        'Pension moyenne : 1 666 €/mois brut (2023)',
        'Âge moyen de départ : 62,7 ans',
        'Ratio cotisants/retraités : 1,8 (1,4 en 2070)',
        '1er poste de dépenses publiques (24,4%)',
        'Déficit du système : -1,7 Md€ en 2024',
      ],
    },
    comparison: {
      eu: [
        { country: 'Italie', value: 16.0 },
        { country: 'Grèce', value: 14.3 },
        { country: 'France', value: 14.5, highlight: true },
        { country: 'Autriche', value: 14.2 },
        { country: 'Portugal', value: 13.8 },
        { country: 'Finlande', value: 13.5 },
        { country: 'Belgique', value: 12.1 },
        { country: 'Espagne', value: 12.0 },
        { country: 'Allemagne', value: 11.3 },
        { country: 'Pays-Bas', value: 7.2 },
      ],
      oecd: [
        { country: 'Italie', value: 16.0 },
        { country: 'France', value: 14.5, highlight: true },
        { country: 'Grèce', value: 14.3 },
        { country: 'Japon', value: 10.2 },
        { country: 'États-Unis', value: 7.5 },
        { country: 'Royaume-Uni', value: 6.8 },
        { country: 'Canada', value: 5.4 },
        { country: 'Corée du Sud', value: 3.6 },
      ],
      insights: [
        'La France consacre 14,5% de son PIB aux retraites, 2ème rang OCDE',
        'Le système français est quasi-exclusivement par répartition (>95%)',
        'L\'Allemagne dépense 3,2 pts de moins (âge départ 67 ans, taux emploi seniors 75%)',
        'L\'âge effectif de départ français (62,7 ans) est ~2 ans sous la moyenne OCDE',
      ],
    },
  },
  {
    id: 'sante',
    name: 'Santé',
    icon: '🏥',
    color: '#a855f7',
    amount: 220,
    description: 'Dépenses de santé publiques (hôpitaux, médicaments, soins de ville)',
    details: [
      'Hôpitaux publics',
      'Soins de ville (médecins, infirmiers)',
      'Médicaments remboursés',
      'Établissements médico-sociaux',
    ],
    france: {
      evolution: [
        { year: '2015', value: 185 },
        { year: '2016', value: 189 },
        { year: '2017', value: 193 },
        { year: '2018', value: 198 },
        { year: '2019', value: 203 },
        { year: '2020', value: 218 },
        { year: '2021', value: 225 },
        { year: '2022', value: 215 },
        { year: '2023', value: 218 },
        { year: '2024', value: 220 },
      ],
      breakdown: [
        { name: 'Hôpitaux', amount: 95, percent: 43.2 },
        { name: 'Soins de ville', amount: 65, percent: 29.5 },
        { name: 'Médicaments', amount: 35, percent: 15.9 },
        { name: 'Autres soins', amount: 25, percent: 11.4 },
      ],
      keyFacts: [
        '12,1% du PIB consacré à la santé (total)',
        '3 000 hôpitaux et cliniques',
        '230 000 médecins en activité',
        'Reste à charge moyen : 7% (le plus bas d\'Europe)',
      ],
    },
    comparison: {
      eu: [
        { country: 'Allemagne', value: 12.7 },
        { country: 'France', value: 12.1, highlight: true },
        { country: 'Belgique', value: 11.1 },
        { country: 'Pays-Bas', value: 10.9 },
        { country: 'Autriche', value: 10.8 },
        { country: 'Suède', value: 10.7 },
        { country: 'Danemark', value: 10.4 },
        { country: 'Espagne', value: 9.5 },
        { country: 'Italie', value: 9.0 },
      ],
      oecd: [
        { country: 'États-Unis', value: 16.6 },
        { country: 'Allemagne', value: 12.7 },
        { country: 'France', value: 12.1, highlight: true },
        { country: 'Suisse', value: 11.8 },
        { country: 'Japon', value: 11.5 },
        { country: 'Canada', value: 11.2 },
        { country: 'Royaume-Uni', value: 10.3 },
      ],
      insights: [
        'La France a le reste à charge le plus faible d\'Europe (7%)',
        'Les USA dépensent 37% de plus pour des résultats similaires',
        'Le Ségur de la santé a ajouté 8,2 Md€ de dépenses annuelles',
        'Le vieillissement augmentera les coûts de 1,5% par an',
      ],
    },
  },
  {
    id: 'protection-sociale',
    name: 'Protection sociale hors retraites',
    icon: '👨‍👩‍👧',
    color: '#ff9f43',
    amount: 231,
    description: 'Aides sociales diverses : famille, chômage, invalidité, pauvreté',
    details: [
      'Allocations familiales',
      'Assurance chômage',
      'Invalidité et handicap',
      'RSA et minima sociaux',
      'Aides au logement (APL)',
    ],
    france: {
      evolution: [
        { year: '2015', value: 195 },
        { year: '2016', value: 198 },
        { year: '2017', value: 200 },
        { year: '2018', value: 203 },
        { year: '2019', value: 207 },
        { year: '2020', value: 235 },
        { year: '2021', value: 240 },
        { year: '2022', value: 228 },
        { year: '2023', value: 230 },
        { year: '2024', value: 231 },
      ],
      breakdown: [
        { name: 'Famille & enfance', amount: 58, percent: 25.1 },
        { name: 'Chômage', amount: 45, percent: 19.5 },
        { name: 'Invalidité & handicap', amount: 50, percent: 21.6 },
        { name: 'Logement (APL)', amount: 38, percent: 16.5 },
        { name: 'Pauvreté & exclusion', amount: 30, percent: 13.0 },
        { name: 'Autres prestations', amount: 10, percent: 4.3 },
      ],
      keyFacts: [
        '14 millions de foyers touchent des aides',
        'Allocations familiales : 12,6 Md€/an',
        'RSA : 2 millions de bénéficiaires',
        'APL : 6 millions de ménages aidés',
      ],
    },
    comparison: {
      eu: [
        { country: 'Danemark', value: 15.2 },
        { country: 'Finlande', value: 14.8 },
        { country: 'France', value: 13.8, highlight: true },
        { country: 'Belgique', value: 12.9 },
        { country: 'Suède', value: 12.5 },
        { country: 'Allemagne', value: 11.2 },
        { country: 'Pays-Bas', value: 10.8 },
        { country: 'Espagne', value: 9.5 },
        { country: 'Italie', value: 9.2 },
      ],
      insights: [
        'La France a un système de protection sociale parmi les plus généreux',
        'Les aides familiales représentent 2,3% du PIB',
        'Le système a amorti le choc COVID avec le chômage partiel',
        'Réforme de l\'assurance chômage : économies de 4 Md€ attendues',
      ],
    },
  },
  {
    id: 'education',
    name: 'Éducation',
    icon: '🎓',
    color: '#4ecdc4',
    amount: 118,
    description: 'Système éducatif de la maternelle à l\'université',
    details: [
      'Écoles primaires',
      'Collèges et lycées',
      'Enseignement supérieur',
      'Formation professionnelle',
    ],
    france: {
      evolution: [
        { year: '2015', value: 98 },
        { year: '2016', value: 100 },
        { year: '2017', value: 103 },
        { year: '2018', value: 106 },
        { year: '2019', value: 109 },
        { year: '2020', value: 110 },
        { year: '2021', value: 113 },
        { year: '2022', value: 115 },
        { year: '2023', value: 117 },
        { year: '2024', value: 118 },
      ],
      breakdown: [
        { name: 'Primaire', amount: 32, percent: 27.1 },
        { name: 'Secondaire', amount: 45, percent: 38.1 },
        { name: 'Supérieur', amount: 28, percent: 23.7 },
        { name: 'Autres', amount: 13, percent: 11.0 },
      ],
      keyFacts: [
        '12,5 millions d\'élèves scolarisés',
        '870 000 enseignants',
        '60 000 établissements',
        'Coût moyen par élève : 9 500 €/an',
      ],
    },
    comparison: {
      eu: [
        { country: 'Suède', value: 6.9 },
        { country: 'Belgique', value: 6.4 },
        { country: 'Danemark', value: 6.1 },
        { country: 'Finlande', value: 5.9 },
        { country: 'France', value: 5.5, highlight: true },
        { country: 'Pays-Bas', value: 5.3 },
        { country: 'Allemagne', value: 4.7 },
        { country: 'Espagne', value: 4.6 },
        { country: 'Italie', value: 4.3 },
      ],
      insights: [
        'La France dépense 5,5% du PIB pour l\'éducation',
        'Les enseignants français sont moins bien payés que la moyenne OCDE',
        'Ratio élèves/enseignant : 19 (moyenne OCDE : 15)',
        'Classement PISA : 23ème sur 79 pays',
      ],
    },
  },
  {
    id: 'defense',
    name: 'Défense',
    icon: '🛡️',
    color: '#45b7d1',
    amount: 55,
    description: 'Armées, équipements militaires, opérations extérieures',
    details: [
      'Personnel militaire',
      'Équipements et armements',
      'Opérations extérieures (OPEX)',
      'Dissuasion nucléaire',
      'Recherche & développement',
    ],
    france: {
      evolution: [
        { year: '2015', value: 42 },
        { year: '2016', value: 43 },
        { year: '2017', value: 44 },
        { year: '2018', value: 46 },
        { year: '2019', value: 48 },
        { year: '2020', value: 50 },
        { year: '2021', value: 51 },
        { year: '2022', value: 52 },
        { year: '2023', value: 54 },
        { year: '2024', value: 55 },
      ],
      breakdown: [
        { name: 'Personnel', amount: 22, percent: 40.0 },
        { name: 'Équipements', amount: 18, percent: 32.7 },
        { name: 'Fonctionnement', amount: 10, percent: 18.2 },
        { name: 'OPEX', amount: 3, percent: 5.5 },
        { name: 'Autres', amount: 2, percent: 3.6 },
      ],
      keyFacts: [
        '270 000 militaires d\'active',
        '2ème armée de l\'UE (après l\'Allemagne en effectifs)',
        '1 porte-avions nucléaire',
        'Force de dissuasion nucléaire',
        'Objectif 2% du PIB atteint en 2024',
      ],
    },
    comparison: {
      eu: [
        { country: 'Grèce', value: 3.0 },
        { country: 'Pologne', value: 2.4 },
        { country: 'Royaume-Uni', value: 2.3 },
        { country: 'France', value: 2.1, highlight: true },
        { country: 'Allemagne', value: 1.6 },
        { country: 'Italie', value: 1.5 },
        { country: 'Espagne', value: 1.3 },
        { country: 'Belgique', value: 1.2 },
      ],
      oecd: [
        { country: 'États-Unis', value: 3.4 },
        { country: 'Grèce', value: 3.0 },
        { country: 'Royaume-Uni', value: 2.3 },
        { country: 'France', value: 2.1, highlight: true },
        { country: 'Corée du Sud', value: 2.8 },
        { country: 'Australie', value: 2.0 },
        { country: 'Canada', value: 1.3 },
        { country: 'Japon', value: 1.1 },
      ],
      insights: [
        'La France respecte l\'objectif OTAN de 2% du PIB',
        'Les USA dépensent 12x plus en valeur absolue',
        'L\'Allemagne augmente son budget de 100 Md€',
        'La France est le 7ème exportateur d\'armes mondial',
      ],
    },
  },
  {
    id: 'dette',
    name: 'Charge de la dette',
    icon: '💳',
    color: '#ffd700',
    amount: 54,
    description: 'Intérêts payés sur la dette publique',
    details: [
      'Obligations Assimilables du Trésor (OAT)',
      'Bons du Trésor',
      'Dette des collectivités locales',
    ],
    france: {
      evolution: [
        { year: '2015', value: 42 },
        { year: '2016', value: 41 },
        { year: '2017', value: 41 },
        { year: '2018', value: 40 },
        { year: '2019', value: 38 },
        { year: '2020', value: 36 },
        { year: '2021', value: 38 },
        { year: '2022', value: 46 },
        { year: '2023', value: 50 },
        { year: '2024', value: 54 },
      ],
      keyFacts: [
        'Dette totale : 3 482 Md€',
        'Taux moyen de la dette : 1,9%',
        'Maturité moyenne : 8,4 ans',
        '4ème poste budgétaire',
        '+50% en 2 ans (remontée des taux)',
      ],
    },
    comparison: {
      eu: [
        { country: 'Italie', value: 3.8 },
        { country: 'Grèce', value: 3.2 },
        { country: 'Espagne', value: 2.5 },
        { country: 'Belgique', value: 2.3 },
        { country: 'France', value: 2.0, highlight: true },
        { country: 'Portugal', value: 1.9 },
        { country: 'Allemagne', value: 1.1 },
        { country: 'Pays-Bas', value: 0.9 },
      ],
      insights: [
        'La charge de la dette a augmenté de 50% en 2 ans',
        'Chaque point de taux en plus = 3 Md€/an',
        'L\'Italie paie 2x plus en % du PIB',
        'Les taux bas ont masqué le problème pendant 10 ans',
      ],
    },
  },
  {
    id: 'politiques-sectorielles',
    name: 'Politiques sectorielles',
    icon: '🏗️',
    color: '#8899a8',
    amount: 191,
    description: 'Transports, agriculture, industrie, aménagement du territoire',
    details: [
      'Infrastructures de transport',
      'Agriculture et pêche',
      'Industrie et commerce',
      'Aménagement du territoire',
      'Recherche et développement',
    ],
    france: {
      evolution: [
        { year: '2015', value: 160 },
        { year: '2016', value: 165 },
        { year: '2017', value: 168 },
        { year: '2018', value: 172 },
        { year: '2019', value: 175 },
        { year: '2020', value: 185 },
        { year: '2021', value: 190 },
        { year: '2022', value: 188 },
        { year: '2023', value: 190 },
        { year: '2024', value: 191 },
      ],
      keyFacts: [
        'France 2030 : 54 Md€ d\'investissements',
        'Entretien du réseau routier : 15 Md€/an',
        'SNCF Réseau : 6 Md€/an',
        'PAC française : 9 Md€/an',
      ],
    },
    comparison: {
      eu: [
        { country: 'France', value: 11.4, highlight: true },
        { country: 'Belgique', value: 10.2 },
        { country: 'Allemagne', value: 9.8 },
        { country: 'Italie', value: 9.5 },
        { country: 'Espagne', value: 8.7 },
        { country: 'Pays-Bas', value: 8.2 },
      ],
      insights: [
        'La France investit fortement dans ses infrastructures',
        'Plan de relance ferroviaire : 100 Md€ sur 10 ans',
        'Décarbonation de l\'industrie : priorité 2024-2030',
      ],
    },
  },
  {
    id: 'affaires-economiques',
    name: 'Affaires économiques',
    icon: '💼',
    color: '#00d4ff',
    amount: 137,
    description: 'Soutien à l\'économie, emploi, entreprises, énergie',
    details: [
      'Aides aux entreprises',
      'Politique de l\'emploi',
      'Énergie et transition',
      'Commerce et export',
    ],
    france: {
      evolution: [
        { year: '2015', value: 95 },
        { year: '2016', value: 98 },
        { year: '2017', value: 100 },
        { year: '2018', value: 105 },
        { year: '2019', value: 110 },
        { year: '2020', value: 165 },
        { year: '2021', value: 155 },
        { year: '2022', value: 145 },
        { year: '2023', value: 140 },
        { year: '2024', value: 137 },
      ],
      keyFacts: [
        'CIR (Crédit Impôt Recherche) : 7 Md€/an',
        'CICE transformé en baisses de charges',
        'Bouclier énergétique : 45 Md€ en 2022-2023',
        'Aides à l\'apprentissage : 6 000€/contrat',
      ],
    },
    comparison: {
      eu: [
        { country: 'France', value: 8.2, highlight: true },
        { country: 'Allemagne', value: 7.5 },
        { country: 'Italie', value: 6.8 },
        { country: 'Belgique', value: 6.5 },
        { country: 'Espagne', value: 5.9 },
      ],
      insights: [
        'La France a fortement soutenu les entreprises pendant le COVID',
        'Le bouclier énergétique a coûté 45 Md€',
        'Objectif : réindustrialisation verte',
      ],
    },
  },
  {
    id: 'services-publics',
    name: 'Services publics généraux',
    icon: '🏛️',
    color: '#dda0dd',
    amount: 132,
    description: 'Administration générale, diplomatie, institutions',
    details: [
      'Administration centrale',
      'Collectivités territoriales',
      'Affaires étrangères',
      'Organes constitutionnels',
    ],
    france: {
      evolution: [
        { year: '2015', value: 115 },
        { year: '2016', value: 118 },
        { year: '2017', value: 120 },
        { year: '2018', value: 122 },
        { year: '2019', value: 125 },
        { year: '2020', value: 128 },
        { year: '2021', value: 130 },
        { year: '2022', value: 131 },
        { year: '2023', value: 132 },
        { year: '2024', value: 132 },
      ],
      keyFacts: [
        '5,7 millions d\'agents publics',
        '35 000 communes en France',
        '13 régions métropolitaines',
        '101 départements',
      ],
    },
    comparison: {
      eu: [
        { country: 'Belgique', value: 9.2 },
        { country: 'France', value: 7.9, highlight: true },
        { country: 'Italie', value: 7.5 },
        { country: 'Allemagne', value: 6.8 },
        { country: 'Espagne', value: 6.2 },
      ],
      insights: [
        'La France a un maillage territorial dense',
        'Réforme de l\'État : simplification en cours',
        'Dématérialisation des services publics',
      ],
    },
  },
  {
    id: 'securite',
    name: 'Ordre & Sécurité',
    icon: '👮',
    color: '#ff4757',
    amount: 45,
    description: 'Police, gendarmerie, justice, système pénitentiaire',
    details: [
      'Police nationale',
      'Gendarmerie',
      'Justice et tribunaux',
      'Prisons',
    ],
    france: {
      evolution: [
        { year: '2015', value: 38 },
        { year: '2016', value: 39 },
        { year: '2017', value: 40 },
        { year: '2018', value: 41 },
        { year: '2019', value: 42 },
        { year: '2020', value: 43 },
        { year: '2021', value: 44 },
        { year: '2022', value: 44 },
        { year: '2023', value: 45 },
        { year: '2024', value: 45 },
      ],
      keyFacts: [
        '150 000 policiers',
        '100 000 gendarmes',
        '8 500 magistrats',
        '70 000 places de prison',
      ],
    },
    comparison: {
      eu: [
        { country: 'France', value: 2.7, highlight: true },
        { country: 'Italie', value: 2.5 },
        { country: 'Espagne', value: 2.3 },
        { country: 'Allemagne', value: 1.8 },
        { country: 'Pays-Bas', value: 1.6 },
      ],
      insights: [
        'La France a un ratio policiers/habitants élevé',
        'Budget justice en augmentation de 8%/an',
        '15 000 places de prison prévues d\'ici 2027',
      ],
    },
  },
  {
    id: 'logement',
    name: 'Logement',
    icon: '🏠',
    color: '#96ceb4',
    amount: 38,
    description: 'Politique du logement, construction, rénovation',
    details: [
      'Construction de logements sociaux',
      'MaPrimeRénov\'',
      'Hébergement d\'urgence',
      'Aides à la pierre',
    ],
    france: {
      evolution: [
        { year: '2015', value: 35 },
        { year: '2016', value: 36 },
        { year: '2017', value: 37 },
        { year: '2018', value: 38 },
        { year: '2019', value: 38 },
        { year: '2020', value: 40 },
        { year: '2021', value: 42 },
        { year: '2022', value: 40 },
        { year: '2023', value: 39 },
        { year: '2024', value: 38 },
      ],
      keyFacts: [
        '5,3 millions de logements sociaux',
        '700 000 rénovations/an visées',
        'MaPrimeRénov\' : 4 Md€/an',
        '200 000 sans-abris hébergés',
      ],
    },
    comparison: {
      eu: [
        { country: 'France', value: 2.3, highlight: true },
        { country: 'Royaume-Uni', value: 2.1 },
        { country: 'Allemagne', value: 1.5 },
        { country: 'Italie', value: 1.2 },
        { country: 'Espagne', value: 0.9 },
      ],
      insights: [
        'La France a un parc social important',
        'Objectif : 500 000 rénovations thermiques/an',
        'Crise du logement neuf en 2024',
      ],
    },
  },
  {
    id: 'culture',
    name: 'Culture & Loisirs',
    icon: '🎭',
    color: '#c4b5fd',
    amount: 37,
    description: 'Culture, médias, sport, jeunesse',
    details: [
      'Musées et patrimoine',
      'Spectacle vivant',
      'Audiovisuel public',
      'Sport et jeunesse',
    ],
    france: {
      evolution: [
        { year: '2015', value: 32 },
        { year: '2016', value: 33 },
        { year: '2017', value: 33 },
        { year: '2018', value: 34 },
        { year: '2019', value: 35 },
        { year: '2020', value: 38 },
        { year: '2021', value: 40 },
        { year: '2022', value: 38 },
        { year: '2023', value: 37 },
        { year: '2024', value: 37 },
      ],
      keyFacts: [
        '1 200 musées en France',
        '45 000 monuments historiques',
        'Audiovisuel public : 4 Md€/an',
        'Pass Culture : 300M€/an',
      ],
    },
    comparison: {
      eu: [
        { country: 'Danemark', value: 2.8 },
        { country: 'France', value: 2.2, highlight: true },
        { country: 'Suède', value: 2.1 },
        { country: 'Pays-Bas', value: 2.0 },
        { country: 'Allemagne', value: 1.8 },
      ],
      insights: [
        'Exception culturelle française',
        'JO Paris 2024 : 4 Md€ d\'investissements',
        'Patrimoine : 1er budget d\'Europe',
      ],
    },
  },
  {
    id: 'environnement',
    name: 'Environnement',
    icon: '🌱',
    color: '#00ff88',
    amount: 32,
    description: 'Protection de l\'environnement, gestion des déchets, eau',
    details: [
      'Transition écologique',
      'Gestion des déchets',
      'Protection de la nature',
      'Eau et assainissement',
    ],
    france: {
      evolution: [
        { year: '2015', value: 22 },
        { year: '2016', value: 23 },
        { year: '2017', value: 24 },
        { year: '2018', value: 25 },
        { year: '2019', value: 27 },
        { year: '2020', value: 28 },
        { year: '2021', value: 30 },
        { year: '2022', value: 31 },
        { year: '2023', value: 32 },
        { year: '2024', value: 32 },
      ],
      keyFacts: [
        'Plan climat : 7 Md€/an',
        'Fonds vert : 2 Md€',
        '11 parcs nationaux',
        '30% du territoire en aires protégées visés',
      ],
    },
    comparison: {
      eu: [
        { country: 'Pays-Bas', value: 2.5 },
        { country: 'Belgique', value: 2.2 },
        { country: 'France', value: 1.9, highlight: true },
        { country: 'Allemagne', value: 1.8 },
        { country: 'Italie', value: 1.5 },
      ],
      insights: [
        'Budget environnement en hausse de 45% en 10 ans',
        'Objectif neutralité carbone 2050',
        'Planification écologique : 33 Md€ prévus',
      ],
    },
  },
]

// Fonction pour récupérer une catégorie par son ID
export function getCategoryById(id: string): DepenseCategory | undefined {
  return DEPENSES_CATEGORIES.find(cat => cat.id === id)
}

// Liste des IDs de catégories pour la génération des pages statiques
export const CATEGORY_IDS = DEPENSES_CATEGORIES.map(cat => cat.id)
